#!/bin/bash

# wminfo launcher: runs all wminfo system plugins

wminfo -p alarm.wmi -u 60 -c -i 2 -b#000000 -f#ffff00 &
sleep 1
wminfo -p biff.wmi -u 5 -c -b#202020 -f#0000ff &
sleep 1
wminfo -p date.wmi -u 1 -s 0 -b#000000 -f#ffff00 &
sleep 1
wminfo -p date-pl.wmi -u 1 -i 2 -b#000000 -f#ffff00 &
sleep 1
wminfo -p date-us.wmi -u 1 -b#000000 -f#ffff00 &
sleep 1
wminfo -p df.wmi -u 5 -s 0 -b#000000 -f#00ff00 &
sleep 1
wminfo -p ip.wmi -b#000000 -f#ff00ff &
sleep 1
wminfo -p "netmon.wmi 5" -u 5 -s 0 -b#000000 -f#ff00ff &
sleep 1
wminfo -p pinboard.wmi -u 15 -i 2 -b#000000 -f#00ffff &
sleep 1
wminfo -p ps.wmi -u 5 -b#000000 -f#ff0000 &
sleep 1
wminfo -p stopwatch.wmi -u 1 -b#000000 -f#ffff00 &
sleep 1
wminfo -p sysmon.wmi -u 5 -s 0 -b#000000 -f#ff0000 &
sleep 1
wminfo -p thinkpad.wmi -u 5 -s 0 -b#000000 -f#00ff00 &
sleep 1
wminfo -p timer.wmi -u 1 -b#000000 -f#ffff00 &
sleep 1
wminfo -p timezone.wmi -u 60 -b#000000 -f#ffff00 &
sleep 1
wminfo -p top.wmi -u 5 -b#000000 -f#ff0000 &
sleep 1
wminfo -p traffic.wmi -u 5 -s 0 -b#000000 -f#ff00ff &
sleep 1
wminfo -p uptime.wmi -u 60 -s 0 -b#000000 -f#ffff00 &

